# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["**/.cfg", "**/hosts", "**/*.json", "**/.env.example", "**/.gitignore", "**/.http", "**/.png", "**/.tf", "**/.terraform.lock.hcl", "**/.conf", "**/.yml", "**/.yaml", "**/.md", "**/.sh", "**/go.mod", "**/go.sum", "**/Dockerfile"]
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"